apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacex-app
  labels:
    app: spacex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacex-app
  template:
    metadata:
      labels:
        app: spacex-app
    spec:
      containers:
        - name: spacex-container
          image: androgeek/spacex:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spacex-service
spec:
  selector:
    app: spacex-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
  type: NodePort

