---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spacex-app
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    interval: 15s
